-- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
 - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_diffbot_launch.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml --junit-prefix=arduino_hardware_controller

============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache
rootdir: /home/nwhit210/omnicar_2_ws
plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3/dist-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/usr/lib/python3/dist-packages/_pytest/python.py:200: in pytest_collect_file
    module: Module = ihook.pytest_pycollect_makemodule(path=path, parent=parent)
/usr/lib/python3/dist-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py:193: in pytest_pycollect_makemodule
    entrypoint = find_launch_test_entrypoint(path)
/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py:186: in find_launch_test_entrypoint
    module = path.pyimport()
/usr/lib/python3/dist-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
../../src/arduino_controller/test/test_diffbot_launch.py:43: in <module>
    from ros2_control_demo_testing.test_utils import (
E   ModuleNotFoundError: No module named 'ros2_control_demo_testing'
- generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml -
=========================== short test summary info ============================
ERROR ../.. - ModuleNotFoundError: No module named 'ros2_control_demo_testing'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.28s ===============================


-- run_test.py: return code 2
-- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml'
