<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.233" timestamp="2025-03-18T14:48:38.746516" hostname="nwhit210"><testcase classname="arduino_hardware_controller.src.arduino_controller.test.test_urdf_xacro" name="test_urdf_xacro" time="0.174"><failure message="AssertionError:  --- XACRO command failed ---&#10;assert 2 == 0&#10; +  where 2 = CompletedProcess(args='/opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share...nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro\n').returncode">def test_urdf_xacro():
        # General Arguments
        description_package = "arduino_hardware_controller"
        description_file = "diffbot.urdf.xacro"
    
        description_file_path = os.path.join(
            get_package_share_directory(description_package), "urdf", description_file
        )
    
        (_, tmp_urdf_output_file) = tempfile.mkstemp(suffix=".urdf")
    
        # Compose `xacro` and `check_urdf` command
        xacro_command = (
            f"{shutil.which('xacro')}" f" {description_file_path}" f" &gt; {tmp_urdf_output_file}"
        )
        check_urdf_command = f"{shutil.which('check_urdf')} {tmp_urdf_output_file}"
    
        # Try to call processes but finally remove the temp file
        try:
            xacro_process = subprocess.run(
                xacro_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True
            )
    
&gt;           assert xacro_process.returncode == 0, " --- XACRO command failed ---"
E           AssertionError:  --- XACRO command failed ---
E           assert 2 == 0
E            +  where 2 = CompletedProcess(args='/opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share...nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro\n').returncode

../../src/arduino_controller/test/test_urdf_xacro.py:62: AssertionError</failure></testcase></testsuite></testsuites>